### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'split'

### ISSUE THREAD

**Issue by pp0236** [rocky/python-xasm#12]
anyone know what i did wrong?

.pyasm
[of.zip](https://github.com/rocky/python-xasm/files/8148749/of.zip)

```
Traceback (most recent call last):
  File "c:\users\d-com\appdata\local\programs\python\python37\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\d-com\appdata\local\programs\python\python37\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\D-Com\AppData\Local\Programs\Python\Python37\Scripts\pyc-xasm.exe\__main__.py", line 7, in <module>
  File "c:\users\d-com\appdata\local\programs\python\python37\lib\site-packages\click\core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "c:\users\d-com\appdata\local\programs\python\python37\lib\site-packages\click\core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "c:\users\d-com\appdata\local\programs\python\python37\lib\site-packages\click\core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "c:\users\d-com\appdata\local\programs\python\python37\lib\site-packages\click\core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "c:\users\d-com\appdata\local\programs\python\python37\lib\site-packages\xasm\xasm_cli.py", line 28, in main
    asm = asm_file(asm_path)
  File "c:\users\d-com\appdata\local\programs\python\python37\lib\site-packages\xasm\assemble.py", line 158, in asm_file
    python_version_pair = version_str_to_tuple(python_version, len=2)
  File "c:\users\d-com\appdata\local\programs\python\python37\lib\site-packages\xdis\version_info.py", line 54, in version_str_to_tuple
    return tuple([int(v) for v in python_version.split(".")[:len]])
AttributeError: 'NoneType' object has no attribute 'split'
```

**Comment by rocky** [comment]
Why is running of.py important?

**Comment by pp0236** [comment]
im just trying to test edit some string

**Comment by rocky** [comment]
Why?

**Comment by pp0236** [comment]
ok

**Comment by pp0236** [comment]
"[questionable activity](https://github.com/rocky/python-xasm/labels/questionable%20activity)"
bruh [overflow.zip](https://github.com/rocky/python-xasm/files/8159399/overflow.zip)
