### ISSUE TITLE
Error with Python 3.8.10 assemble file

### ISSUE THREAD

**Issue by m0hamedessam** [rocky/python-xasm#9]
pydisasm version 5.0.10
Python bytecode 3.8 (3413)
 Disassembled from Python 3.8.10 (default, May  5 2021, 03:01:07) 

i use pydisasm --format xasm but i got error when i try to compile back pyc

```
Traceback (most recent call last):
  File "c:\users\m0hamed\desktop\python-xasm-master\python-xasm-master\xasm\assemble.py", line 419, in create_code
    inst.arg = label[target] - offset
KeyError: '(to'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\m0hamed\AppData\Local\Programs\Python\Python38-32\Scripts\pyc-xasm-script.py", line 11, in <module>
    load_entry_point('xasm', 'console_scripts', 'pyc-xasm')()
  File "c:\users\m0hamed\appdata\local\programs\python\python38-32\lib\site-packages\click\core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "c:\users\m0hamed\appdata\local\programs\python\python38-32\lib\site-packages\click\core.py", line 782, in main
    rv = self.invoke(ctx)
  File "c:\users\m0hamed\appdata\local\programs\python\python38-32\lib\site-packages\click\core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "c:\users\m0hamed\appdata\local\programs\python\python38-32\lib\site-packages\click\core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "c:\users\m0hamed\desktop\python-xasm-master\python-xasm-master\xasm\xasm_cli.py", line 28, in main
    asm = asm_file(asm_path)
  File "c:\users\m0hamed\desktop\python-xasm-master\python-xasm-master\xasm\assemble.py", line 150, in asm_file
    co = create_code(asm, label, backpatch_inst)
  File "c:\users\m0hamed\desktop\python-xasm-master\python-xasm-master\xasm\assemble.py", line 425, in create_code
    err("Label %s not found" % target, inst, i)
  File "c:\users\m0hamed\desktop\python-xasm-master\python-xasm-master\xasm\assemble.py", line 364, in err
    raise RuntimeError(msg)
RuntimeError: Label (to not found. Instruction 0:
 188: SETUP_FINALLY     (to
```

pyasm file here
https://we.tl/t-ntUBq3RuHD

Any idea ???

**Comment by rocky** [comment]
Sorry, I don't have time for user questions. Except maybe for people who support the projects. Try StackOverflow?
